apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: y37whtqiz-python 
  janus-idp.io/tekton: y37whtqiz-python
  backstage.io/kubernetes-id: y37whtqiz-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: y37whtqiz-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml